//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyodhyaYatra_Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AyodhyaYatra_Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 Kosi Yatra.
        /// </summary>
        public static string _14KosiYatra {
            get {
                return ResourceManager.GetString("14KosiYatra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Kosi Parikrama.
        /// </summary>
        public static string _5KosiParikrama {
            get {
                return ResourceManager.GetString("5KosiParikrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 84 Kosi Parikrama.
        /// </summary>
        public static string _84KosiParikrama {
            get {
                return ResourceManager.GetString("84KosiParikrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aashram.
        /// </summary>
        public static string Aashram {
            get {
                return ResourceManager.GetString("Aashram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Ayodhya.
        /// </summary>
        public static string AboutAyodhya {
            get {
                return ResourceManager.GetString("AboutAyodhya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayodhya, the former capital of the Avadh area, holds a particular place in the hearts of Lord Rama&apos;s followers because Rama, the descendant of Manu&apos;s Surya Vansh, is closely linked to its history. According to the Atharvaveda, the gods created this holy place, which was as prosperous as paradise. According to scripture, numerous great kings ruled the capital city of Kosaldesh, including Ikshvaku, Prithu, Mandhata, Harishchandra, Sagar, Bhagirath, Raghu, Dileep, Dashrath, and Ram. During their reign, the kin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airways Booking.
        /// </summary>
        public static string AirwaysBooking {
            get {
                return ResourceManager.GetString("AirwaysBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambulance.
        /// </summary>
        public static string Ambulance {
            get {
                return ResourceManager.GetString("Ambulance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM.
        /// </summary>
        public static string ATM {
            get {
                return ResourceManager.GetString("ATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Gallery.
        /// </summary>
        public static string AudioGallery {
            get {
                return ResourceManager.GetString("AudioGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayodhya counted among the seven most sacred cities of ancient India, is situated on the right bank of the river Saryu, once the capital of Avadh region.
        /// </summary>
        public static string AyodhyacountedDescription1 {
            get {
                return ResourceManager.GetString("AyodhyacountedDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Our Mobile App :.
        /// </summary>
        public static string AyodhyacountedDescription2 {
            get {
                return ResourceManager.GetString("AyodhyacountedDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayodhya counted among the seven most sacred cities of ancient India, is situated on the right bank of the river Saryu, once the capital of Avadh region. Ayodhya holds a place of pride among the devotees of Lord Rama, who was a descendant of the Surya Vansh which is believed to have been founded by Manu, the lawgiver of the Hindus......
        /// </summary>
        public static string AyodhyaOverviewDescription {
            get {
                return ResourceManager.GetString("AyodhyaOverviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhawan.
        /// </summary>
        public static string Bhawan {
            get {
                return ResourceManager.GetString("Bhawan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat Riding Booking.
        /// </summary>
        public static string BoatRidingBooking {
            get {
                return ResourceManager.GetString("BoatRidingBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Services.
        /// </summary>
        public static string BookServices {
            get {
                return ResourceManager.GetString("BookServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddhist.
        /// </summary>
        public static string Buddhist {
            get {
                return ResourceManager.GetString("Buddhist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Ticket Booking.
        /// </summary>
        public static string BusTicketBooking {
            get {
                return ResourceManager.GetString("BusTicketBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Helpline.
        /// </summary>
        public static string ChildHelpline {
            get {
                return ResourceManager.GetString("ChildHelpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hon&apos;ble Chief Minister, Uttar Pradesh.
        /// </summary>
        public static string CM {
            get {
                return ResourceManager.GetString("CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM Helpline.
        /// </summary>
        public static string CMHelpline {
            get {
                return ResourceManager.GetString("CMHelpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Policy.
        /// </summary>
        public static string CopyrightPolicy {
            get {
                return ResourceManager.GetString("CopyrightPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©2024 Department of Tourism, Ayodhya, Uttar Pradesh, India | All rights reserved..
        /// </summary>
        public static string CopyrightsDescription {
            get {
                return ResourceManager.GetString("CopyrightsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covid-19 Helpline No..
        /// </summary>
        public static string Covid19HelplineNo {
            get {
                return ResourceManager.GetString("Covid19HelplineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Visitors.
        /// </summary>
        public static string DailyVisitors {
            get {
                return ResourceManager.GetString("DailyVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of Tourism, Ayodhya, Uttar Pradesh.
        /// </summary>
        public static string DepartmentofTourism {
            get {
                return ResourceManager.GetString("DepartmentofTourism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed and hosted by.
        /// </summary>
        public static string Developedandhostedby {
            get {
                return ResourceManager.GetString("Developedandhostedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOs &amp; Don’ts.
        /// </summary>
        public static string DOsAndDont {
            get {
                return ResourceManager.GetString("DOsAndDont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Institutions.
        /// </summary>
        public static string EducationalInstitutions {
            get {
                return ResourceManager.GetString("EducationalInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Services.
        /// </summary>
        public static string EmergencyServices {
            get {
                return ResourceManager.GetString("EmergencyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment &amp;amp; Shopping Places.
        /// </summary>
        public static string EntertainmentShoppingPlaces {
            get {
                return ResourceManager.GetString("EntertainmentShoppingPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famous-Temple.
        /// </summary>
        public static string FamousTemple {
            get {
                return ResourceManager.GetString("FamousTemple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQs.
        /// </summary>
        public static string FAQs {
            get {
                return ResourceManager.GetString("FAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festival and Events.
        /// </summary>
        public static string FestivalEvents {
            get {
                return ResourceManager.GetString("FestivalEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Services.
        /// </summary>
        public static string FindServices {
            get {
                return ResourceManager.GetString("FindServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Tourism.
        /// </summary>
        public static string ForTourism {
            get {
                return ResourceManager.GetString("ForTourism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghat.
        /// </summary>
        public static string Ghat {
            get {
                return ResourceManager.GetString("Ghat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayodhya have over 62 different Ghat..
        /// </summary>
        public static string Ghatcount {
            get {
                return ResourceManager.GetString("Ghatcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Donate for Charity.
        /// </summary>
        public static string GoToDonateforCharity {
            get {
                return ResourceManager.GetString("GoToDonateforCharity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of Uttar Pradesh.
        /// </summary>
        public static string GovernmentofUttarPradesh {
            get {
                return ResourceManager.GetString("GovernmentofUttarPradesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growing.
        /// </summary>
        public static string Growing {
            get {
                return ResourceManager.GetString("Growing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over 12,0000 men and women visit daliy ayodhya..
        /// </summary>
        public static string Growingcount {
            get {
                return ResourceManager.GetString("Growingcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gurdwara.
        /// </summary>
        public static string Gurdwara {
            get {
                return ResourceManager.GetString("Gurdwara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpline.
        /// </summary>
        public static string Helpline {
            get {
                return ResourceManager.GetString("Helpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpline Numbers.
        /// </summary>
        public static string HelplineNumbers {
            get {
                return ResourceManager.GetString("HelplineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heritage.
        /// </summary>
        public static string Heritage {
            get {
                return ResourceManager.GetString("Heritage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical &amp;amp; Religious Places.
        /// </summary>
        public static string HistoricalReligiousPlaces {
            get {
                return ResourceManager.GetString("HistoricalReligiousPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital.
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitals.
        /// </summary>
        public static string Hospitals {
            get {
                return ResourceManager.GetString("Hospitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Booking.
        /// </summary>
        public static string HotelBooking {
            get {
                return ResourceManager.GetString("HotelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels, Resorts and Restaurants.
        /// </summary>
        public static string HotelsResortsandRestaurants {
            get {
                return ResourceManager.GetString("HotelsResortsandRestaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Links.
        /// </summary>
        public static string ImportantLinks {
            get {
                return ResourceManager.GetString("ImportantLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Ayodhya.
        /// </summary>
        public static string inAyodhya {
            get {
                return ResourceManager.GetString("inAyodhya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incredible India.
        /// </summary>
        public static string IncredibleIndia {
            get {
                return ResourceManager.GetString("IncredibleIndia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industries.
        /// </summary>
        public static string Industries {
            get {
                return ResourceManager.GetString("Industries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Facts.
        /// </summary>
        public static string KeyFacts {
            get {
                return ResourceManager.GetString("KeyFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kila.
        /// </summary>
        public static string Kila {
            get {
                return ResourceManager.GetString("Kila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kund.
        /// </summary>
        public static string Kund {
            get {
                return ResourceManager.GetString("Kund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahal.
        /// </summary>
        public static string Mahal {
            get {
                return ResourceManager.GetString("Mahal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MH Toll Free No..
        /// </summary>
        public static string MHTollFreeNo {
            get {
                return ResourceManager.GetString("MHTollFreeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry of Tourism.
        /// </summary>
        public static string MinistryofTourism {
            get {
                return ResourceManager.GetString("MinistryofTourism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near by Places.
        /// </summary>
        public static string NearbyPlaces {
            get {
                return ResourceManager.GetString("NearbyPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News &amp;amp; Events.
        /// </summary>
        public static string NewsEvents {
            get {
                return ResourceManager.GetString("NewsEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Booking.
        /// </summary>
        public static string OnlineBooking {
            get {
                return ResourceManager.GetString("OnlineBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Attraction.
        /// </summary>
        public static string OtherAttraction {
            get {
                return ResourceManager.GetString("OtherAttraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Attraction.
        /// </summary>
        public static string OurAttraction {
            get {
                return ResourceManager.GetString("OurAttraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview and Concept.
        /// </summary>
        public static string OverviewandConcept {
            get {
                return ResourceManager.GetString("OverviewandConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview of Ayodhya Dham.
        /// </summary>
        public static string OverviewAyodhyaDham {
            get {
                return ResourceManager.GetString("OverviewAyodhyaDham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park.
        /// </summary>
        public static string Park {
            get {
                return ResourceManager.GetString("Park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personality of Ayodhya.
        /// </summary>
        public static string PersonalityofAyodhya {
            get {
                return ResourceManager.GetString("PersonalityofAyodhya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallery.
        /// </summary>
        public static string PhotoGallery {
            get {
                return ResourceManager.GetString("PhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hon&apos;ble Prime Minister, India.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string Policies {
            get {
                return ResourceManager.GetString("Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &amp; Media.
        /// </summary>
        public static string PressAndMedia {
            get {
                return ResourceManager.GetString("PressAndMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Pass.
        /// </summary>
        public static string PrintPass {
            get {
                return ResourceManager.GetString("PrintPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Utilities.
        /// </summary>
        public static string PublicUtilities {
            get {
                return ResourceManager.GetString("PublicUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string QuickLinks {
            get {
                return ResourceManager.GetString("QuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railway Booking.
        /// </summary>
        public static string RailwayBooking {
            get {
                return ResourceManager.GetString("RailwayBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railway &amp;amp; Transport.
        /// </summary>
        public static string RailwayTransport {
            get {
                return ResourceManager.GetString("RailwayTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Form.
        /// </summary>
        public static string RegistrationForm {
            get {
                return ResourceManager.GetString("RegistrationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saryu-Arti.
        /// </summary>
        public static string SaryuArti {
            get {
                return ResourceManager.GetString("SaryuArti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shri Narendra Modi.
        /// </summary>
        public static string ShriNarendraModi {
            get {
                return ResourceManager.GetString("ShriNarendraModi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shri Yogi Adityanath.
        /// </summary>
        public static string ShriYogiAdityanath {
            get {
                return ResourceManager.GetString("ShriYogiAdityanath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Attraction.
        /// </summary>
        public static string SpecialAttraction {
            get {
                return ResourceManager.GetString("SpecialAttraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPIT.
        /// </summary>
        public static string SPIT {
            get {
                return ResourceManager.GetString("SPIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Classification.
        /// </summary>
        public static string StarClassification {
            get {
                return ResourceManager.GetString("StarClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support us, we need your help..
        /// </summary>
        public static string Support1 {
            get {
                return ResourceManager.GetString("Support1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May ram bless you! Thank you. Those who (in charity) spend of their goods by night and by day.
        /// </summary>
        public static string Support2 {
            get {
                return ResourceManager.GetString("Support2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taj Mahal.
        /// </summary>
        public static string TajMahal {
            get {
                return ResourceManager.GetString("TajMahal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100+ Temples in Ayodhya.
        /// </summary>
        public static string Templecount {
            get {
                return ResourceManager.GetString("Templecount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temples.
        /// </summary>
        public static string Temples {
            get {
                return ResourceManager.GetString("Temples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360 degree Gallery.
        /// </summary>
        public static string ThreeSixtydegreeGallery {
            get {
                return ResourceManager.GetString("ThreeSixtydegreeGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourist Attractions.
        /// </summary>
        public static string TouristAttractions {
            get {
                return ResourceManager.GetString("TouristAttractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourist Guide.
        /// </summary>
        public static string TouristGuide {
            get {
                return ResourceManager.GetString("TouristGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourist Guide by Map.
        /// </summary>
        public static string TouristGuidebyMap {
            get {
                return ResourceManager.GetString("TouristGuidebyMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Package Booking.
        /// </summary>
        public static string TourPackageBooking {
            get {
                return ResourceManager.GetString("TourPackageBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        public static string Upcoming {
            get {
                return ResourceManager.GetString("Upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPSRTC.
        /// </summary>
        public static string UPSRTC {
            get {
                return ResourceManager.GetString("UPSRTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPSTDC Portal.
        /// </summary>
        public static string UPSTDCPortal {
            get {
                return ResourceManager.GetString("UPSTDCPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP Tourism No..
        /// </summary>
        public static string UPTourismNo {
            get {
                return ResourceManager.GetString("UPTourismNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Gallery.
        /// </summary>
        public static string VideoGallery {
            get {
                return ResourceManager.GetString("VideoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Registration.
        /// </summary>
        public static string VisitorRegistration {
            get {
                return ResourceManager.GetString("VisitorRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Ayodhya Dham.
        /// </summary>
        public static string WelcomeAyodhyaDham {
            get {
                return ResourceManager.GetString("WelcomeAyodhyaDham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What We Offer.
        /// </summary>
        public static string WhatWeOffer {
            get {
                return ResourceManager.GetString("WhatWeOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women Comm. No..
        /// </summary>
        public static string WomenCommNo {
            get {
                return ResourceManager.GetString("WomenCommNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women Helpline.
        /// </summary>
        public static string WomenHelpline {
            get {
                return ResourceManager.GetString("WomenHelpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatra in Ayodhya.
        /// </summary>
        public static string YatrainAyodhya {
            get {
                return ResourceManager.GetString("YatrainAyodhya", resourceCulture);
            }
        }
    }
}
