//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyodhyaYatra_Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AyodhyaYatra_Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Ayodhya.
        /// </summary>
        public static string AboutAyodhya {
            get {
                return ResourceManager.GetString("AboutAyodhya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM.
        /// </summary>
        public static string ATM {
            get {
                return ResourceManager.GetString("ATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Gallery.
        /// </summary>
        public static string AudioGallery {
            get {
                return ResourceManager.GetString("AudioGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayodhya counted among the seven most sacred cities of ancient India, is situated on the right bank of the river Saryu, once the capital of Avadh region.
        /// </summary>
        public static string AyodhyacountedDescription1 {
            get {
                return ResourceManager.GetString("AyodhyacountedDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Our Mobile App :.
        /// </summary>
        public static string AyodhyacountedDescription2 {
            get {
                return ResourceManager.GetString("AyodhyacountedDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayodhya counted among the seven most sacred cities of ancient India, is situated on the right bank of the river Saryu, once the capital of Avadh region. Ayodhya holds a place of pride among the devotees of Lord Rama, who was a descendant of the Surya Vansh which is believed to have been founded by Manu, the lawgiver of the Hindus......
        /// </summary>
        public static string AyodhyaOverviewDescription {
            get {
                return ResourceManager.GetString("AyodhyaOverviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hon&apos;ble Chief Minister, Uttar Pradesh.
        /// </summary>
        public static string CM {
            get {
                return ResourceManager.GetString("CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Policy.
        /// </summary>
        public static string CopyrightPolicy {
            get {
                return ResourceManager.GetString("CopyrightPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©2024 Department of Tourism, Ayodhya, Uttar Pradesh, India | All rights reserved..
        /// </summary>
        public static string CopyrightsDescription {
            get {
                return ResourceManager.GetString("CopyrightsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of Tourism, Ayodhya, Uttar Pradesh.
        /// </summary>
        public static string DepartmentofTourism {
            get {
                return ResourceManager.GetString("DepartmentofTourism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed and hosted by.
        /// </summary>
        public static string Developedandhostedby {
            get {
                return ResourceManager.GetString("Developedandhostedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOs &amp; Don’ts.
        /// </summary>
        public static string DOsAndDont {
            get {
                return ResourceManager.GetString("DOsAndDont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Institutions.
        /// </summary>
        public static string EducationalInstitutions {
            get {
                return ResourceManager.GetString("EducationalInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Services.
        /// </summary>
        public static string EmergencyServices {
            get {
                return ResourceManager.GetString("EmergencyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment &amp;amp; Shopping Places.
        /// </summary>
        public static string EntertainmentShoppingPlaces {
            get {
                return ResourceManager.GetString("EntertainmentShoppingPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQs.
        /// </summary>
        public static string FAQs {
            get {
                return ResourceManager.GetString("FAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghat.
        /// </summary>
        public static string Ghat {
            get {
                return ResourceManager.GetString("Ghat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of Uttar Pradesh.
        /// </summary>
        public static string GovernmentofUttarPradesh {
            get {
                return ResourceManager.GetString("GovernmentofUttarPradesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpline.
        /// </summary>
        public static string Helpline {
            get {
                return ResourceManager.GetString("Helpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical &amp;amp; Religious Places.
        /// </summary>
        public static string HistoricalReligiousPlaces {
            get {
                return ResourceManager.GetString("HistoricalReligiousPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitals.
        /// </summary>
        public static string Hospitals {
            get {
                return ResourceManager.GetString("Hospitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels, Resorts and Restaurants.
        /// </summary>
        public static string HotelsResortsandRestaurants {
            get {
                return ResourceManager.GetString("HotelsResortsandRestaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Ayodhya.
        /// </summary>
        public static string inAyodhya {
            get {
                return ResourceManager.GetString("inAyodhya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industries.
        /// </summary>
        public static string Industries {
            get {
                return ResourceManager.GetString("Industries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Facts.
        /// </summary>
        public static string KeyFacts {
            get {
                return ResourceManager.GetString("KeyFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kund.
        /// </summary>
        public static string Kund {
            get {
                return ResourceManager.GetString("Kund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News &amp;amp; Events.
        /// </summary>
        public static string NewsEvents {
            get {
                return ResourceManager.GetString("NewsEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Booking.
        /// </summary>
        public static string OnlineBooking {
            get {
                return ResourceManager.GetString("OnlineBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Attraction.
        /// </summary>
        public static string OtherAttraction {
            get {
                return ResourceManager.GetString("OtherAttraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview and Concept.
        /// </summary>
        public static string OverviewandConcept {
            get {
                return ResourceManager.GetString("OverviewandConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview of Ayodhya Dham.
        /// </summary>
        public static string OverviewAyodhyaDham {
            get {
                return ResourceManager.GetString("OverviewAyodhyaDham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personality of Ayodhya.
        /// </summary>
        public static string PersonalityofAyodhya {
            get {
                return ResourceManager.GetString("PersonalityofAyodhya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallery.
        /// </summary>
        public static string PhotoGallery {
            get {
                return ResourceManager.GetString("PhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hon&apos;ble Prime Minister, India.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string Policies {
            get {
                return ResourceManager.GetString("Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &amp; Media.
        /// </summary>
        public static string PressAndMedia {
            get {
                return ResourceManager.GetString("PressAndMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Pass.
        /// </summary>
        public static string PrintPass {
            get {
                return ResourceManager.GetString("PrintPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Utilities.
        /// </summary>
        public static string PublicUtilities {
            get {
                return ResourceManager.GetString("PublicUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string QuickLinks {
            get {
                return ResourceManager.GetString("QuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railway &amp;amp; Transport.
        /// </summary>
        public static string RailwayTransport {
            get {
                return ResourceManager.GetString("RailwayTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Form.
        /// </summary>
        public static string RegistrationForm {
            get {
                return ResourceManager.GetString("RegistrationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shri Narendra Modi.
        /// </summary>
        public static string ShriNarendraModi {
            get {
                return ResourceManager.GetString("ShriNarendraModi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shri Yogi Adityanath.
        /// </summary>
        public static string ShriYogiAdityanath {
            get {
                return ResourceManager.GetString("ShriYogiAdityanath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPIT.
        /// </summary>
        public static string SPIT {
            get {
                return ResourceManager.GetString("SPIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temples.
        /// </summary>
        public static string Temples {
            get {
                return ResourceManager.GetString("Temples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360 degree Gallery.
        /// </summary>
        public static string ThreeSixtydegreeGallery {
            get {
                return ResourceManager.GetString("ThreeSixtydegreeGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourist Guide.
        /// </summary>
        public static string TouristGuide {
            get {
                return ResourceManager.GetString("TouristGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourist Guide by Map.
        /// </summary>
        public static string TouristGuidebyMap {
            get {
                return ResourceManager.GetString("TouristGuidebyMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPSTDC Portal.
        /// </summary>
        public static string UPSTDCPortal {
            get {
                return ResourceManager.GetString("UPSTDCPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Gallery.
        /// </summary>
        public static string VideoGallery {
            get {
                return ResourceManager.GetString("VideoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Registration.
        /// </summary>
        public static string VisitorRegistration {
            get {
                return ResourceManager.GetString("VisitorRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Ayodhya Dham.
        /// </summary>
        public static string WelcomeAyodhyaDham {
            get {
                return ResourceManager.GetString("WelcomeAyodhyaDham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatra in Ayodhya.
        /// </summary>
        public static string YatrainAyodhya {
            get {
                return ResourceManager.GetString("YatrainAyodhya", resourceCulture);
            }
        }
    }
}
